using AgentAIUtility.Chat;
using AgentAIUtility.Entity;
using Microsoft.Agents.AI;
using Microsoft.Agents.AI.Workflows;
using Microsoft.Extensions.AI;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace AIAgentExample.Example
{
    public static class WorkflowExample
    {
        #region Data structures

        /// <summary>
        /// Represents the result of spam detection.
        /// </summary>
        public sealed class DetectionResult
        {
            [JsonPropertyName("is_spam")]
            public bool IsSpam { get; set; }
            [JsonPropertyName("reason")]
            public string Reason { get; set; } = string.Empty;
            // Email ID is generated by the executor, not the agent
            [JsonIgnore]
            public string EmailId { get; set; } = string.Empty;
            public override string ToString()
            {
                return JsonSerializer.Serialize(this);
            }
        }

        /// <summary>
        /// Represents an email.
        /// </summary>
        internal sealed class Email
        {
            [JsonPropertyName("email_id")]
            public string EmailId { get; set; } = string.Empty;
            [JsonPropertyName("email_content")]
            public string EmailContent { get; set; } = string.Empty;
            public override string ToString()
            {
                return JsonSerializer.Serialize(this);
            }
        }

        /// <summary>
        /// Represents the response from the email assistant.
        /// </summary>
        public sealed class EmailResponse
        {
            [JsonPropertyName("response")]
            public string Response { get; set; } = string.Empty;
            public override string ToString()
            {
                return JsonSerializer.Serialize(this);
            }
        }

        /// <summary>
        /// Constants for shared state scopes.
        /// </summary>
        internal static class EmailStateConstants
        {
            public const string EmailStateScope = "EmailState";
        }

        #endregion

        #region Agents

        /// <summary>
        /// Creates a spam detection agent.
        /// </summary>
        /// <returns>A ChatClientAgent configured for spam detection</returns>
        public static ChatClientAgent GetSpamDetectionAgent(IChatClient chatClient)
        {
            var o = new ChatClientAgentOptions()
            {
                ChatOptions = new()
                {
                    Instructions = "You are a spam detection assistant that identifies spam emails.",
                    ResponseFormat = ChatResponseFormat.ForJsonSchema(AIJsonUtilities.CreateJsonSchema(typeof(DetectionResult)))
                }
            };
            var a = new ChatClientAgent(chatClient, o);
            return a;
        }

        /// <summary>
        /// Creates an email assistant agent.
        /// </summary>
        /// <returns>A ChatClientAgent configured for email assistance</returns>
        public static ChatClientAgent GetEmailAssistantAgent(IChatClient chatClient)
        {
            var o = new ChatClientAgentOptions()
            {
                ChatOptions = new()
                {
                    Instructions = "You are an email assistant that helps users draft professional responses to emails.",
                    ResponseFormat = ChatResponseFormat.ForJsonSchema(AIJsonUtilities.CreateJsonSchema(typeof(EmailResponse)))
                }
            };
            var a = new ChatClientAgent(chatClient, o);
            return a;
        }

        /// <summary>
        /// Implement a test IChatClient
        /// without calling the LLM
        /// </summary>
        public static IChatClient GetChatClient()
        {
            TestChatClient chatClient = new();
            chatClient.GetContent = (messages) =>
            {
                ChatMessage msgSystem = messages
                    .Where(m => m.Role == ChatRole.System)
                    .First();

                ChatMessage msgUser = messages.Last();

                var sys = msgSystem.Text;
                var usr = msgUser.Text;
                string resp = "{}";
                // called by SpamDetectionAgent based on system prompt
                if (sys.Contains("spam detection assistant"))
                {
                    var d = new DetectionResult();
                    d.IsSpam = usr.Contains("You've won $1,000,000!") ? true : d.IsSpam;
                    d.Reason = d.IsSpam ? "Phishing" : "";
                    resp = JsonSerializer.Serialize(d);
                }
                // called by EmailAssistantAgent based on system prompt
                else if (sys.Contains("an email assistant"))
                {
                    var e = new EmailResponse();
                    e.Response = "Thank you for your request.";
                    resp = JsonSerializer.Serialize(e);
                }

                return new ChatMessage(ChatRole.Assistant, resp);
            };
            return chatClient;
        }

        #endregion

        #region Test Agent

        public static async Task<object?> TestSpamDetectionAgent()
        {
            IChatClient chatClient = GetChatClient();
            var agent = GetSpamDetectionAgent(chatClient);
            string emailContent = "Congratulations! You've won $1,000,000! Click here to claim your prize now!";
            var res = await agent.RunAsync<DetectionResult>(emailContent);
            Console.WriteLine($"Is Spam : {res.Result.IsSpam}");
            return res;
        }

        public static async Task<object?> TestEmailAssistantAgent()
        {
            IChatClient chatClient = GetChatClient();
            var agent = GetEmailAssistantAgent(chatClient);
            string emailContent = "Test email received";
            var res = await agent.RunAsync<EmailResponse>(emailContent);
            Console.WriteLine($"Email Response : {res.Result.Response}");
            return res;
        }

        #endregion

        #region Executor

        /// <summary>
        /// Executor that detects spam using an AI agent.
        /// </summary>
        internal sealed partial class SpamDetectionExecutor : Executor
        {
            private readonly AIAgent _spamDetectionAgent;

            public SpamDetectionExecutor(AIAgent spamDetectionAgent) :
                base("SpamDetectionExecutor")
                {
                    this._spamDetectionAgent = spamDetectionAgent;
                }

            [MessageHandler]
            private async ValueTask<DetectionResult> HandleAsync(
                ChatMessage message,
                IWorkflowContext context, 
                CancellationToken cancellationToken = default)
            {
                // Generate a random email ID and store the email content to shared state
                var newEmail = new Email
                {
                    EmailId = Guid.NewGuid().ToString("N"),
                    EmailContent = message.Text
                };
                await context.QueueStateUpdateAsync(
                    newEmail.EmailId, 
                    newEmail, 
                    scopeName: EmailStateConstants.EmailStateScope);

                // Invoke the agent for spam detection
                var response = await this._spamDetectionAgent.RunAsync(message);

                var detectionResult = JsonSerializer.Deserialize<DetectionResult>(response.Text);
                detectionResult!.EmailId = newEmail.EmailId;
                return detectionResult;
            }

            protected override ProtocolBuilder ConfigureProtocol(ProtocolBuilder protocolBuilder)
            {
                protocolBuilder
                    .RouteBuilder
                        .AddHandler<ChatMessage, DetectionResult>(HandleAsync);
                return protocolBuilder;
            }
        }

        /// <summary>
        /// Executor that assists with email responses using an AI agent.
        /// </summary>
        internal sealed partial class EmailAssistantExecutor : Executor
        {
            private readonly AIAgent _emailAssistantAgent;
            public EmailAssistantExecutor(AIAgent emailAssistantAgent) :
                base("EmailAssistantExecutor")
                {
                    this._emailAssistantAgent = emailAssistantAgent;
                }

            [MessageHandler]
            public async ValueTask<EmailResponse> HandleAsync(
                DetectionResult message,
                IWorkflowContext context, 
                CancellationToken cancellationToken = default)
            {
                if (message.IsSpam)
                {
                    throw new ArgumentException("This executor should only handle non-spam messages.");
                }

                // Retrieve the email content from shared state
                var email = await context.ReadStateAsync<Email>(
                    message.EmailId, 
                    scopeName:
                    EmailStateConstants.EmailStateScope
                ) ?? throw new InvalidOperationException("Email not found.");

                // Invoke the agent to draft a response
                var response = await this._emailAssistantAgent.RunAsync(email.EmailContent);

                var emailResponse = JsonSerializer.Deserialize<EmailResponse>(response.Text);
                return emailResponse!;
            }

            protected override ProtocolBuilder ConfigureProtocol(ProtocolBuilder protocolBuilder)
            {
                protocolBuilder
                    .RouteBuilder
                        .AddHandler<DetectionResult, EmailResponse>(HandleAsync);
                return protocolBuilder;
            }
        }

        /// <summary>
        /// Executor that sends emails.
        /// </summary>
        internal sealed partial class SendEmailExecutor : Executor
        {
            public SendEmailExecutor() : base("SendEmailExecutor") { }

            [MessageHandler]
            public async ValueTask HandleAsync(
                EmailResponse message, 
                IWorkflowContext context, 
                CancellationToken cancellationToken = default) =>
                    await context.YieldOutputAsync($"Email sent: {message.Response}");

            protected override ProtocolBuilder ConfigureProtocol(ProtocolBuilder protocolBuilder)
            {
                protocolBuilder
                    .YieldsOutput<string>()
                    .RouteBuilder
                        .AddHandler<EmailResponse>(HandleAsync);
                return protocolBuilder;
            }
        }

        /// <summary>
        /// Executor that handles spam messages.
        /// </summary>
        internal sealed partial class HandleSpamExecutor : Executor
        {
            public HandleSpamExecutor() : base("HandleSpamExecutor") { }

            [MessageHandler]
            public async ValueTask HandleAsync(
                DetectionResult message, 
                IWorkflowContext  context, 
                CancellationToken cancellationToken = default)
            {
                if (message.IsSpam)
                {
                    await context.YieldOutputAsync($"Email marked as spam: { message.Reason}");
                }
                else
                {
                    throw new ArgumentException("This executor should only handle spam messages.");
                }
            }

            protected override ProtocolBuilder ConfigureProtocol(ProtocolBuilder protocolBuilder)
            {
                protocolBuilder
                    .YieldsOutput<string>()
                    .RouteBuilder
                        .AddHandler<DetectionResult>(HandleAsync);
                return protocolBuilder;
            }
        }

        #endregion

        #region Workflow

        public static WorkflowBuilder BuildWorkflow()
        {
            IChatClient chatClient = GetChatClient();

            // Create agents
            AIAgent spamDetectionAgent = GetSpamDetectionAgent(chatClient);
            AIAgent emailAssistantAgent = GetEmailAssistantAgent(chatClient);

            // Create executors
            var spamDetectionExecutor = new SpamDetectionExecutor(spamDetectionAgent);
            var emailAssistantExecutor = new EmailAssistantExecutor(emailAssistantAgent);
            var sendEmailExecutor = new SendEmailExecutor();
            var handleSpamExecutor = new HandleSpamExecutor();

            Func<DetectionResult?, bool> GetCondition(bool expectedResult) => 
                (DetectionResult? res) => 
                    res?.IsSpam == expectedResult;

            // Build the workflow with conditional edges
            var workflow = new WorkflowBuilder(spamDetectionExecutor)
                // Non-spam path: route to email assistant when IsSpam = false
                .AddEdge(
                    spamDetectionExecutor,
                    emailAssistantExecutor,
                    condition: GetCondition(expectedResult: false))
                .AddEdge(emailAssistantExecutor, sendEmailExecutor)
                // Spam path: route to spam handler when IsSpam = true
                .AddEdge(
                    spamDetectionExecutor,
                    handleSpamExecutor,
                    condition: GetCondition(expectedResult: true))
                .WithOutputFrom(handleSpamExecutor, sendEmailExecutor)
                .WithName("Email Replier")
                .WithDescription("Respond to an email message if the message is not a SPAM.");

            return workflow;
        }

        #endregion

        public static async Task<object?> RunWorkflow()
        {
            WorkflowBuilder builder = BuildWorkflow();

            ChatSession session = new ChatSession();
            session.WorkflowBuilder = builder;
            session.Title = "Run example - Responding to email workflow";
            session.AIModel = new() { ServiceId = "Local Test Agent" };

            WorkflowService service = new WorkflowService(session);

            IEnumerable<string> prompts = [
                    "Congratulations! You've won $1,000,000! Click here to claim your prize now!",
                    "This is not a spam email"
                ];

            await service.StartChat(prompts);

            return null;
        }
    }
}
